export default function TermsOfServicePage() {
  return (
    <main className="min-h-screen bg-background text-foreground pb-24">
      {/* Header */}
      <section className="py-24 px-6 text-center hero-gradient">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-5xl font-bold mb-6 text-gradient-secondary">
            Terms of Service
          </h1>
          <p className="text-muted-foreground text-lg">
            Please read these terms carefully before using Earnings Call
            Insights.
          </p>
        </div>
      </section>

      {/* Content */}
      <section className="py-16 px-6">
        <div className="max-w-4xl mx-auto space-y-8">
          {/* 1 */}
          <div className="card-premium p-6">
            <h2 className="text-xl font-semibold mb-3">
              1. Acceptance of Terms
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              By accessing or using InvestorEye, you agree to be bound by these
              Terms of Service and our Privacy Policy. If you do not agree, you
              must not use the platform.
            </p>
          </div>

          {/* 2 */}
          <div className="card-premium p-6">
            <h2 className="text-xl font-semibold mb-3">
              2. Description of Service
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              InvestorEye provides AI-powered financial analysis, including
              earnings call summarization, sentiment analysis, market insights,
              and data visualization tools.
            </p>
          </div>

          {/* 3 */}
          <div className="card-premium p-6">
            <h2 className="text-xl font-semibold mb-3">
              3. User Responsibilities
            </h2>
            <ul className="text-muted-foreground space-y-2 list-disc pl-5">
              <li>Use the platform only for lawful purposes</li>
              <li>Do not attempt to reverse engineer or abuse APIs</li>
              <li>Do not overload or disrupt system performance</li>
              <li>Ensure accuracy of any data you submit</li>
            </ul>
          </div>

          {/* 4 */}
          <div className="card-premium p-6">
            <h2 className="text-xl font-semibold mb-3">
              4. AI-Generated Content
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              The insights provided by our AI models are for informational
              purposes only and should not be considered financial advice. Users
              are responsible for their own investment decisions.
            </p>
          </div>

          {/* 5 */}
          <div className="card-premium p-6">
            <h2 className="text-xl font-semibold mb-3">5. Data Sources</h2>
            <p className="text-muted-foreground leading-relaxed">
              We integrate third-party APIs such as OpenAI, AWS, Yahoo Finance,
              Alpha Vantage, and other financial data providers. We do not
              guarantee the accuracy or completeness of external data sources.
            </p>
          </div>

          {/* 6 */}
          <div className="card-premium p-6">
            <h2 className="text-xl font-semibold mb-3">
              6. Limitations of Liability
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              We are not liable for any financial losses, damages, or decisions
              made based on insights generated by the platform. All usage is at
              your own risk.
            </p>
          </div>

          {/* 7 */}
          <div className="card-premium p-6">
            <h2 className="text-xl font-semibold mb-3">
              7. Service Availability
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              We do not guarantee uninterrupted access. The platform may
              experience downtime due to maintenance, updates, or third-party
              service failures.
            </p>
          </div>

          {/* 8 */}
          <div className="card-premium p-6">
            <h2 className="text-xl font-semibold mb-3">
              8. Account Termination
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              We reserve the right to suspend or terminate access if users
              violate these terms or misuse the platform.
            </p>
          </div>

          {/* 9 */}
          <div className="card-premium p-6">
            <h2 className="text-xl font-semibold mb-3">9. Changes to Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              We may update these Terms of Service from time to time. Continued
              use of the platform constitutes acceptance of any changes.
            </p>
          </div>

          {/* Footer */}
          <div className="text-center text-sm text-muted-foreground pt-6">
            Last updated: April 2026
          </div>
        </div>
      </section>
    </main>
  );
}
